api-version: 1.13
main: com.github.hornta.wild.Wild
name: Wild
version: ${project.version}
author: hornta
softdepend:  [WorldBorder, Vault]
commands:
  wild:
permissions:
  wild.wild:
    default: true
  wild.player:
    default: op
  wild.world:
    default: op
  wild.bypasscooldown:
    default: false
  wild.bypasscharge:
    default: false
  wild.reload:
    default: op