api-version: 1.15
main: com.github.hornta.wild.WildPlugin
name: Wild
version: ${project.version}
author: hornta
softdepend:  [WorldBorder, Vault]
commands:
  wild:
    aliases:
      - rtp
permissions:
  wild.wild:
    default: true
  wild.player:
    default: op
  wild.world:
    default: op
  wild.bypasscooldown:
    default: false
  wild.bypasscharge:
    default: false
  wild.reload:
    default: op
  wild.info:
    default: op