package com.github.hornta.wild.config;

public enum ConfigKey {
  LANGUAGE,
  COOLDOWN,
  TRIES,
  NO_BORDER_SIZE,
  USE_VANILLA_WORLD_BORDER,
  IMMORTAL_DURATION_AFTER_TELEPORT,
  CHARGE_ENABLED,
  CHARGE_AMOUNT,
  DISABLED_WORLDS,
  WILD_ON_FIRST_JOIN_ENABLED,
  WILD_ON_FIRST_JOIN_WORLD,
  WILD_ON_DEATH_ENABLED,
  WILD_ON_DEATH_WORLD
}
